# Generated by Django 5.2.4 on 2025-09-03 22:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porch',
            name='owner',
        ),
        migrations.AddField(
            model_name='porch',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porch',
            name='owner_email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porch',
            name='owner_name',
            field=models.CharField(default='austin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='porch',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='porch',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='porch',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='porch',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='porch',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='porch',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
