# Generated by Django 5.2.4 on 2025-10-15 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0002_remove_porch_owner_porch_approved_porch_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
