# Generated by Django 5.2.4 on 2025-10-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0003_porch_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='original_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
