# Generated by Django 5.2.4 on 2026-01-17 19:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0004_porch_original_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='after_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porch',
            name='childrens_activities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porch',
            name='info_booth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porch',
            name='number_of_performances',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='porch',
            name='owner_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='porch',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porch',
            name='porch_picture',
            field=models.ImageField(blank=True, null=True, upload_to='porches/'),
        ),
        migrations.AddField(
            model_name='porch',
            name='porta_potty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porch',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porch',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
