# Generated by Django 5.2.4 on 2026-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0005_porch_after_party_porch_childrens_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
