# Generated by Django 5.2.4 on 2026-01-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0006_tempupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='neighbors_hosting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porch',
            name='other_info',
            field=models.TextField(blank=True),
        ),
    ]
