# Generated by Django 5.2.4 on 2026-01-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0007_porch_neighbors_hosting_porch_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('text', 'Text Message'), ('knock', 'Knock on Door')], default='email', max_length=10),
        ),
    ]
