# Generated by Django 5.2.4 on 2026-01-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0008_porch_preferred_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porch',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('text', 'Text Message')], default='email', max_length=10),
        ),
    ]
