# Generated by Django 5.2.4 on 2026-03-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0010_performer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
