# Generated by Django 5.2.4 on 2026-03-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0011_porch_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porch',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
