# Generated by Django 5.2.4 on 2026-03-20 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0014_alter_performer_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performer',
            name='genre',
            field=models.CharField(choices=[('aerialist', 'Aerialist'), ('acoustic', 'Acoustic'), ('alternative', 'Alternative'), ('americana', 'Americana'), ('bellydance', 'Bellydance'), ('bluegrass', 'Bluegrass'), ('blues', 'Blues'), ('cajun', 'Cajun'), ('classical', 'Classical'), ('classic_rock', 'Classic Rock'), ('comedy', 'Comedy'), ('contemporary', 'Contemporary'), ('country', 'Country'), ('dance_electronic', 'Dance / Electronic / House'), ('dark_jazz', 'Dark Jazz'), ('dj', 'DJ'), ('drag', 'Drag'), ('drumming', 'Drumming'), ('dubstep', 'Dubstep'), ('eclectic', 'Eclectic'), ('electronic', 'Electronic'), ('flamenco', 'Flamenco'), ('folk', 'Folk'), ('funk', 'Funk'), ('hardcore', 'Hardcore'), ('hip_hop_rap', 'Hip-Hop / Rap'), ('house', 'House'), ('indie', 'Indie'), ('jazz', 'Jazz'), ('latin', 'Latin'), ('mariachi', 'Mariachi'), ('medicine_drum', 'Medicine Drum'), ('metal', 'Metal'), ('painter', 'Painter'), ('piano', 'Piano'), ('poetry_spoken_word', 'Poetry / Spoken Word'), ('pop', 'Pop'), ('post_human_rock', 'Post Human Civilization Rock'), ('prog_rock', 'Prog Rock'), ('psychedelic_rock', 'Psychedelic Rock'), ('punk', 'Punk'), ('rnb', 'R & B'), ('reggae', 'Reggae'), ('rock', 'Rock'), ('rock_and_roll', 'Rock and Roll'), ('rockabilly', 'Rockabilly'), ('shoegaze', 'Shoegaze'), ('ska', 'Ska'), ('salsa_cumbia', 'Salsa / Cumbia'), ('soul_blues', 'Soul / Blues'), ('sound_bath', 'Sound Bath Practitioner'), ('singer_songwriter', 'Singer Songwriter'), ('swing', 'Swing'), ('tech_house', 'Tech House'), ('techno', 'Techno'), ('thrash_metal', 'Thrash Metal'), ('trap', 'Trap'), ('trip_hop', 'Trip Hop'), ('vocals', 'Vocals'), ('yoga', 'Yoga'), ('zydeco', 'Zydeco'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
