# Generated by Django 5.2.4 on 2026-03-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0015_alter_performer_created_by_alter_performer_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='performer',
            name='genres',
            field=models.ManyToManyField(blank=True, to='porchfestcore.genremodel'),
        ),
    ]
