# Generated by Django 5.2.4 on 2026-03-24 03:55

from django.db import migrations

def forwards(apps, schema_editor):
    Performer = apps.get_model('porchfestcore', 'Performer')
    Genre = apps.get_model('porchfestcore', 'GenreModel')

    for obj in Performer.objects.all():
        if obj.genre:
            try:
                genre = Genre.objects.get(slug=obj.genre)
                obj.genres.add(genre)
            except Genre.DoesNotExist:
                pass


def backwards(apps, schema_editor):
    Performer = apps.get_model('porchfestcore', 'Performer')

    for obj in Performer.objects.all():
        first = obj.genres.first()
        if first:
            obj.genre = first.slug
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0016_genremodel_performer_genres'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]