# Generated by Django 5.2.4 on 2026-03-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0017_auto_20260323_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreModel',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='porch',
            options={'verbose_name': 'Porch', 'verbose_name_plural': 'Porches'},
        ),
        migrations.RemoveField(
            model_name='performer',
            name='genre',
        ),
    ]
