# Generated by Django 5.2.4 on 2026-04-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0018_rename_genremodel_genre_alter_porch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porch',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='porchfestcore.performer'),
        ),
    ]
