# Generated by Django 5.2.4 on 2026-04-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0019_porch_number_alter_performance_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
