# Generated by Django 5.2.4 on 2026-04-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0020_performer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
