# Generated by Django 5.2.4 on 2026-06-02 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porchfestcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performances', models.ManyToManyField(blank=True, related_name='itineraries', to='porchfestcore.performance')),
            ],
        ),
    ]
