# Generated by Django 5.2.4 on 2026-06-02 15:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('member_count', models.IntegerField(default=1)),
                ('instruments', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='performers/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, to='porchfestcore.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Porch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('text', 'Text Message')], default='email', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('porch_picture', models.ImageField(blank=True, null=True, upload_to='porches/')),
                ('vendor', models.BooleanField(default=False)),
                ('childrens_activities', models.BooleanField(default=False)),
                ('number_of_performances', models.IntegerField(default=1)),
                ('after_party', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('info_booth', models.BooleanField(default=False)),
                ('porta_potty', models.BooleanField(default=False)),
                ('sponsored', models.BooleanField(default=False)),
                ('drinking_water', models.BooleanField(default=False)),
                ('bicycle_repair', models.BooleanField(default=False)),
                ('neighbors_hosting', models.BooleanField(default=False)),
                ('other_info', models.TextField(blank=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('number', models.SmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Porch',
                'verbose_name_plural': 'Porches',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='porchfestcore.performer')),
                ('porch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='porchfestcore.porch')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porchfestcore.performer')),
                ('porch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porchfestcore.porch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
