# Generated by Django 5.2.4 on 2026-06-02 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porchfestcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(upload_to='sponsors/logos/')),
                ('map_icon', models.ImageField(blank=True, upload_to='sponsors/map_icons')),
                ('level', models.IntegerField(choices=[(0, 'Event'), (1, 'Diamond'), (2, 'Platinum'), (3, 'Gold'), (4, 'Community')], default=4)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('porch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor', to='porchfestcore.porch')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
    ]
