# Generated by Django 5.2.4 on 2025-09-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_sponsor_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=255)),
            ],
        ),
    ]
