# Generated by Django 5.2.4 on 2026-03-25 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0018_rename_genremodel_genre_alter_porch_options_and_more'),
        ('website', '0003_porchinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='porch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porches', to='porchfestcore.porch'),
        ),
    ]
