# Generated by Django 5.2.4 on 2026-03-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sponsor_porch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.CharField(choices=[('event', 'Event'), ('diamond', 'Diamond'), ('platinum', 'Platinum'), ('gold', 'Gold'), ('community', 'Community')], default='community', max_length=20),
        ),
    ]
