# Generated by Django 5.2.4 on 2026-03-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0018_rename_genremodel_genre_alter_porch_options_and_more'),
        ('website', '0005_alter_sponsor_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='porch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor', to='porchfestcore.porch'),
        ),
    ]
