# Generated by Django 5.2.4 on 2026-03-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_sponsor_porch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='map_icon',
            field=models.ImageField(blank=True, upload_to='sponsors/map_icons'),
        ),
    ]
