# Generated by Django 5.2.4 on 2026-04-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_sponsor_map_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.IntegerField(choices=[(0, 'Event'), (1, 'Diamond'), (2, 'Platinum'), (3, 'Gold'), (4, 'Community')], default=4),
        ),
    ]
