# Generated by Django 5.2.4 on 2026-06-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchfestcore', '0002_performer_email_performer_phone_number_and_more'),
        ('porchpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='owner_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='invitation',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='porchfestcore.performer'),
        ),
    ]
